### ISSUE TITLE
Tests not passing on GHC 8 / Stackage nightly

### ISSUE THREAD

**Issue by seagreen** [pharpend/editor-open#2]
The error:

```
[~/code/mine/editor-open]traveller@nivian $ stack exec editor-open-test_yaml_file
editor-open-test_yaml_file: vi: spawnProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

The `stack.yml` config:

```
resolver: nightly-2016-07-04
nix:
  enable: true
  shell-file: shell.nix
```

`shell.nix`:

```
with import <nixpkgs> {};

haskell.lib.buildStackProject {
  name = "none";
  ghc = haskell.compiler.ghc801;
  buildInputs = [
    zlib.dev
    zlib.out
  ];
}
```
